-- MySQL Script generated by MySQL Workbench
-- Mon Nov 20 12:08:34 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(45) NOT NULL DEFAULT 'USER',
  PRIMARY KEY (`idUtilisateur`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produits` (
  `idProduits` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `marque` VARCHAR(45) NOT NULL,
  `categorie` VARCHAR(45) NOT NULL,
  `poid` DOUBLE NOT NULL,
  `prix` DOUBLE NOT NULL,
  `couleur` VARCHAR(45) NULL,
  `taille` VARCHAR(45) NULL,
  `description` VARCHAR(1000) NOT NULL,
  `image` VARCHAR(1000) NOT NULL,
  `Produitscol` VARCHAR(45) NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idProduits`),
  INDEX `fk_Produits_Utilisateur_idx` (`Utilisateur_idUtilisateur` ASC),
  CONSTRAINT `fk_Produits_Utilisateur`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Commande` (
  `idCommande` INT NOT NULL AUTO_INCREMENT,
  `date_commande` DATETIME NOT NULL,
  `date_payer` DATETIME NULL,
  `date_livraison` DATETIME NULL,
  `prix_livraison` DOUBLE NOT NULL,
  `prix_sous_total` DOUBLE NOT NULL,
  `prix_total` DOUBLE NOT NULL,
  `statut` VARCHAR(45) NOT NULL,
  `info` VARCHAR(1000) NULL,
  `nom_acheteur` VARCHAR(45) NOT NULL,
  `add_acheteur` VARCHAR(1000) NOT NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idCommande`, `Utilisateur_idUtilisateur`),
  INDEX `fk_Commande_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC),
  CONSTRAINT `fk_Commande_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `mydb`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detailCommande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detailCommande` (
  `quantite` INT NOT NULL,
  `Commande_idCommande` INT NOT NULL,
  `Commande_Utilisateur_idUtilisateur` INT NOT NULL,
  `Produits_idProduits` INT NOT NULL,
  INDEX `fk_detailCommande_Commande1_idx` (`Commande_idCommande` ASC, `Commande_Utilisateur_idUtilisateur` ASC),
  INDEX `fk_detailCommande_Produits1_idx` (`Produits_idProduits` ASC),
  CONSTRAINT `fk_detailCommande_Commande1`
    FOREIGN KEY (`Commande_idCommande` , `Commande_Utilisateur_idUtilisateur`)
    REFERENCES `mydb`.`Commande` (`idCommande` , `Utilisateur_idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detailCommande_Produits1`
    FOREIGN KEY (`Produits_idProduits`)
    REFERENCES `mydb`.`Produits` (`idProduits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stocage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stocage` (
  `quantite` INT NOT NULL,
  `Produits_idProduits` INT NOT NULL,
  INDEX `fk_Stocage_Produits1_idx` (`Produits_idProduits` ASC),
  CONSTRAINT `fk_Stocage_Produits1`
    FOREIGN KEY (`Produits_idProduits`)
    REFERENCES `mydb`.`Produits` (`idProduits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entree` (
  `idEntree` INT NOT NULL,
  `quantite` INT NOT NULL,
  `prixUnite` DOUBLE NOT NULL,
  `date` DATE NOT NULL,
  `Produits_idProduits` INT NOT NULL,
  PRIMARY KEY (`idEntree`),
  INDEX `fk_Entree_Produits1_idx` (`Produits_idProduits` ASC),
  CONSTRAINT `fk_Entree_Produits1`
    FOREIGN KEY (`Produits_idProduits`)
    REFERENCES `mydb`.`Produits` (`idProduits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
